"""add discount_price and best_seller

Revision ID: 586632952440
Revises: d956a19850bb
Create Date: 2026-06-12 15:56:43.965919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586632952440'
down_revision: Union[str, None] = 'd956a19850bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('best_seller', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'best_seller')
    op.drop_column('products', 'discount_price')
    # ### end Alembic commands ###
