"""add image to categories

Revision ID: 708cb3c08631
Revises: c1d4b8958d27
Create Date: 2026-06-23 13:13:50.435371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708cb3c08631'
down_revision: Union[str, None] = 'c1d4b8958d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
