"""add short_description to categories

Revision ID: c1d4b8958d27
Revises: 70429d506162
Create Date: 2026-06-23 12:14:27.999522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d4b8958d27'
down_revision: Union[str, None] = '70429d506162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('short_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'short_description')
    # ### end Alembic commands ###
